common:
	make -C common
wtftp:
	make -C wtftp
wthread:
	make -C wthread

all:common wtftp wthread
	echo make all sucess!
clean:
	make clean -C common
	make clean -C wtftp
	make clean -C wthread